version: '3'
services:
  rocket:
    image: rocket-app2
    environment:
      MONGODB_URI: set-your-own
      MONGODB_PROTOCOL: mongodb+srv
      MONGODB_USERNAME: set-your-own
      MONGODB_PASSWORD: set-your-own
      ROCKET_ADDRESS: 0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    network_mode: bridge
