version: '3'
services:
  rocket:
    image: rocket-app2
    environment:
      MONGODB_URI: mongodb
      MONGODB_RUST_APP: rust-app-2
      MONGODB_PROTOCOL: mongodb
      MONGODB_PORT: 27017
      ROCKET_ADDRESS: 0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    external_links:
      - mongodb
    network_mode: bridge
