[default]
port = 80
secret_key = "BKWoiGHZ6BGpyOeVvWwrit3NjHt/FuapqKa9Ws5Ol5g="

[debug]
port = 80
secret_key = "BKWoiGHZ6BGpyOeVvWwrit3NjHt/FuapqKa9Ws5Ol5g="

[release]
port = 80
secret_key = "BKWoiGHZ6BGpyOeVvWwrit3NjHt/FuapqKa9Ws5Ol5g="