apiVersion: v1
kind: Service
metadata:
  name: mongo-port
spec:
  type: NodePort
  ports:
    - targetPort: 27017 
      port: 27017
      nodePort: 30009
  selector:
    app-type: db
    