apiVersion: v1
kind: Service
metadata:
  name: mongo-clusterip
  labels:
    app-type: mongo-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app-type: db
