apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/mongo-volume/
