apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 250M
  accessModes:
    - ReadWriteOnce

