name: Upload build artifacts

on: 
  workflow_dispatch:
    branches: ["master"]
jobs:
  upload:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.build.outputs.app-version }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-rocket-cache"
      - name: Build
        id: build
        run: |
          cargo build --release --verbose
          cp Rocket.toml target/release/Rocket.toml
          appVersion=$(grep -m 1 version Cargo.toml | grep -e '[0-9].[0-9].[0-9]' -o)
          echo $appVersion
          echo 'app-version=${appVersion}' >> $GITHUB_OUTPUT ';'
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ app-version }}
          path: target/release