name: Upload build artifacts

on: 
  workflow_dispatch:
    branches: ["master"]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-rocket-cache"
      - name: Build
        run: |
          cargo build --release --verbose
          ls target
          ls target/release
          cp Rocket.toml target/release/Rocket.toml
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/release