name: Upload build artifacts

on: 
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      VERSION: "0.0.0"
    steps:
      - run: ls
      - uses: ./.github/workflows/build.yml
      - name: Set version
        run: |
          appVersion=$(grep -m 1 version Cargo.toml | grep -e '[0-9].[0-9].[0-9]' -o)
          echo "VERSION=$appVersion" >> $GITHUB_ENV
          echo $VERSION
          echo ${{ env.VERSION }}
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ env.VERSION }}
          path: target/release